# Data pre-processing
### Step 1: Import necessary libraries and load the dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv ("/kaggle/input/datasets/adhamad0/spaceship-train/train.csv")
train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

### Step 2: Drop irrelevant columns

'PassengerId' and 'Name' are only identifiers and have no predictive value.

In [3]:
train = train.drop (columns = ['PassengerId', 'Name'])

train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

### Step 3: Handle missing values

- numerical data use median imputation
- categorical/boolean data use mode imputation

In [4]:
# Split the columns into numerical or categorical
num_cols = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
cat_cols = ["HomePlanet", "CryoSleep", "Cabin", "Destination", "VIP"]

# Fill in missing values for numerical data
train [num_cols] = train [num_cols].fillna (train [num_cols].median ())

# Fill in missing values for categorical data
for col in cat_cols:
    train [col] = train [col].fillna (train [col].mode ()[0])

train

/tmp/ipykernel_17/1738119241.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train [col] = train [col].fillna (train [col].mode ()[0])

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

### Step 4: Convert boolean values into numerical values

In [5]:
train ["CryoSleep"] = train ["CryoSleep"].astype (int)
train ["VIP"] = train ["VIP"].astype (int)
train ["Transported"] = train ["Transported"].astype (int)

train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,0,B/0/P,TRAPPIST-1e,39.0,0,0.0,0.0,0.0,0.0,0.0,0
1,Earth,0,F/0/S,TRAPPIST-1e,24.0,0,109.0,9.0,25.0,549.0,44.0,1
2,Europa,0,A/0/S,TRAPPIST-1e,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0
3,Europa,0,A/0/S,TRAPPIST-1e,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0
4,Earth,0,F/1/S,TRAPPIST-1e,16.0,0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,0,A/98/P,55 Cancri e,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0
8689,Earth,1,G/1499/S,PSO J318.5-22,18.0,0,0.0,0.0,0.0,0.0,0.0,0
8690,Earth,0,G/1500/S,TRAPPIST-1e,26.0,0,0.0,0.0,1872.0,1.0,0.0,1
8691,Europa,0,E/608/S,55 Cancri e,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0
8692,Europa,0,E/608/S,TRAPPIST-1e,44.0,0,126.0,4688.0,0.0,0.0,12.0,1

### Step 5: Handle cabin

In [6]:
train [["Deck", "Num", "Side"]] = train ["Cabin"].str.split ("/", expand = True)
train = train.drop (columns = "Cabin")

train

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Deck,Num,Side
0,Europa,0,TRAPPIST-1e,39.0,0,0.0,0.0,0.0,0.0,0.0,0,B,0,P
1,Earth,0,TRAPPIST-1e,24.0,0,109.0,9.0,25.0,549.0,44.0,1,F,0,S
2,Europa,0,TRAPPIST-1e,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0,A,0,S
3,Europa,0,TRAPPIST-1e,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0,A,0,S
4,Earth,0,TRAPPIST-1e,16.0,0,303.0,70.0,151.0,565.0,2.0,1,F,1,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,0,55 Cancri e,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0,A,98,P
8689,Earth,1,PSO J318.5-22,18.0,0,0.0,0.0,0.0,0.0,0.0,0,G,1499,S
8690,Earth,0,TRAPPIST-1e,26.0,0,0.0,0.0,1872.0,1.0,0.0,1,G,1500,S
8691,Europa,0,55 Cancri e,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0,E,608,S
8692,Europa,0,TRAPPIST-1e,44.0,0,126.0,4688.0,0.0,0.0,12.0,1,E,608,S

### Step 6: Convert categorical data into numerical data
- One-hot encoding

In [7]:
cat_cols = ["HomePlanet", "Destination", "Deck", "Side"]
train = pd.get_dummies (train, columns = cat_cols, drop_first = True)

train

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Num,...,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Side_S
0,0,39.0,0,0.0,0.0,0.0,0.0,0.0,0,0,...,False,True,True,False,False,False,False,False,False,False
1,0,24.0,0,109.0,9.0,25.0,549.0,44.0,1,0,...,False,True,False,False,False,False,True,False,False,True
2,0,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0,0,...,False,True,False,False,False,False,False,False,False,True
3,0,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0,0,...,False,True,False,False,False,False,False,False,False,True
4,0,16.0,0,303.0,70.0,151.0,565.0,2.0,1,1,...,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0,98,...,False,False,False,False,False,False,False,False,False,False
8689,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0,1499,...,True,False,False,False,False,False,False,True,False,True
8690,0,26.0,0,0.0,0.0,1872.0,1.0,0.0,1,1500,...,False,True,False,False,False,False,False,True,False,True
8691,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0,608,...,False,False,False,False,False,True,False,False,False,True
8692,0,44.0,0,126.0,4688.0,0.0,0.0,12.0,1,608,...,False,True,False,False,False,True,False,False,False,True

### Step 7: Separate X and y

In [8]:
X = train.drop (columns = "Transported")
y = train ["Transported"]

### Step 8: Feature Scaling
- Z-score standardisation

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler ()
X_scaled = scaler.fit_transform (X)

# Model selection
### Logistic Regression (forward stepwise)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_scaled = pd.DataFrame (X_scaled, columns = X.columns)

X_train, X_val, y_train, y_val = train_test_split (X_scaled, y, test_size = 0.2, random_state = 42)

features = list (X.columns)
selected_features = []
remaining_features = features.copy ()
best_score = 0

while len (remaining_features) > 0:
    scores = []

    for feature in remaining_features:
        current_features = selected_features + [feature]

        model = LogisticRegression (max_iter = 1000)
        model.fit (X_train [current_features], y_train)

        y_pred = model.predict (X_val [current_features])
        accuracy = accuracy_score (y_val, y_pred)
        
        scores.append ((accuracy, feature))
    
    scores.sort (reverse = True)
    best_new_score, best_feature = scores [0]

    if best_new_score <= best_score:
        break

    selected_features.append (best_feature)
    remaining_features.remove (best_feature)
    best_score = best_new_score

print ("Final accuracy score: ", best_score)
print ("Selected features: ", selected_features)

model.fit(X_train[selected_features], y_train)

Final accuracy score:  0.7889591719378953
Selected features:  ['CryoSleep', 'FoodCourt', 'VRDeck', 'Spa', 'RoomService', 'Deck_E', 'Deck_F', 'Deck_T']

LogisticRegression(max_iter=1000)

# Test data loading

### Step 1: load the data set

In [11]:
test = pd.read_csv ("/kaggle/input/competitions/spaceship-titanic/test.csv")
test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

### Step 2: Drop irrelevant columns

In [12]:
passenger_ids = test["PassengerId"]
test = test.drop (columns = ['PassengerId', 'Name'])

test

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4272,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0
4273,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0
4274,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0
4275,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0
4276,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0

### Step 3: Fill missing values

In [13]:
# Split the columns into numerical or categorical
num_cols = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
cat_cols = ["HomePlanet", "CryoSleep", "Cabin", "Destination", "VIP"]

# Fill in missing values for numerical data
test [num_cols] = test [num_cols].fillna (test [num_cols].median ())

# Fill in missing values for categorical data
for col in cat_cols:
    test [col] = test [col].fillna (test [col].mode ()[0])

test

/tmp/ipykernel_17/2696335778.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test [col] = test [col].fillna (test [col].mode ()[0])

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4272,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0
4273,Earth,False,G/160/P,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0
4274,Mars,True,D/296/P,55 Cancri e,26.0,False,0.0,0.0,0.0,0.0,0.0
4275,Europa,False,D/297/P,TRAPPIST-1e,26.0,False,0.0,2680.0,0.0,0.0,523.0
4276,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0

### Step 4: Convert boolean values into numerical values

In [14]:
test ["CryoSleep"] = test ["CryoSleep"].astype (int)
test ["VIP"] = test ["VIP"].astype (int)

test

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Earth,1,G/3/S,TRAPPIST-1e,27.0,0,0.0,0.0,0.0,0.0,0.0
1,Earth,0,F/4/S,TRAPPIST-1e,19.0,0,0.0,9.0,0.0,2823.0,0.0
2,Europa,1,C/0/S,55 Cancri e,31.0,0,0.0,0.0,0.0,0.0,0.0
3,Europa,0,C/1/S,TRAPPIST-1e,38.0,0,0.0,6652.0,0.0,181.0,585.0
4,Earth,0,F/5/S,TRAPPIST-1e,20.0,0,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4272,Earth,1,G/1496/S,TRAPPIST-1e,34.0,0,0.0,0.0,0.0,0.0,0.0
4273,Earth,0,G/160/P,TRAPPIST-1e,42.0,0,0.0,847.0,17.0,10.0,144.0
4274,Mars,1,D/296/P,55 Cancri e,26.0,0,0.0,0.0,0.0,0.0,0.0
4275,Europa,0,D/297/P,TRAPPIST-1e,26.0,0,0.0,2680.0,0.0,0.0,523.0
4276,Earth,1,G/1498/S,PSO J318.5-22,43.0,0,0.0,0.0,0.0,0.0,0.0

### Step 5: Handle cabin

In [15]:
test [["Deck", "Num", "Side"]] = test ["Cabin"].str.split ("/", expand = True)
test = test.drop (columns = "Cabin")

test

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Deck,Num,Side
0,Earth,1,TRAPPIST-1e,27.0,0,0.0,0.0,0.0,0.0,0.0,G,3,S
1,Earth,0,TRAPPIST-1e,19.0,0,0.0,9.0,0.0,2823.0,0.0,F,4,S
2,Europa,1,55 Cancri e,31.0,0,0.0,0.0,0.0,0.0,0.0,C,0,S
3,Europa,0,TRAPPIST-1e,38.0,0,0.0,6652.0,0.0,181.0,585.0,C,1,S
4,Earth,0,TRAPPIST-1e,20.0,0,10.0,0.0,635.0,0.0,0.0,F,5,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,Earth,1,TRAPPIST-1e,34.0,0,0.0,0.0,0.0,0.0,0.0,G,1496,S
4273,Earth,0,TRAPPIST-1e,42.0,0,0.0,847.0,17.0,10.0,144.0,G,160,P
4274,Mars,1,55 Cancri e,26.0,0,0.0,0.0,0.0,0.0,0.0,D,296,P
4275,Europa,0,TRAPPIST-1e,26.0,0,0.0,2680.0,0.0,0.0,523.0,D,297,P
4276,Earth,1,PSO J318.5-22,43.0,0,0.0,0.0,0.0,0.0,0.0,G,1498,S

### Step 6: Convert categorical data into numerical data
- One-hot encoding

In [16]:
cat_cols = ["HomePlanet", "Destination", "Deck", "Side"]
test = pd.get_dummies (test, columns = cat_cols, drop_first = True)

test

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Num,HomePlanet_Europa,...,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Side_S
0,1,27.0,0,0.0,0.0,0.0,0.0,0.0,3,False,...,False,True,False,False,False,False,False,True,False,True
1,0,19.0,0,0.0,9.0,0.0,2823.0,0.0,4,False,...,False,True,False,False,False,False,True,False,False,True
2,1,31.0,0,0.0,0.0,0.0,0.0,0.0,0,True,...,False,False,False,True,False,False,False,False,False,True
3,0,38.0,0,0.0,6652.0,0.0,181.0,585.0,1,True,...,False,True,False,True,False,False,False,False,False,True
4,0,20.0,0,10.0,0.0,635.0,0.0,0.0,5,False,...,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,34.0,0,0.0,0.0,0.0,0.0,0.0,1496,False,...,False,True,False,False,False,False,False,True,False,True
4273,0,42.0,0,0.0,847.0,17.0,10.0,144.0,160,False,...,False,True,False,False,False,False,False,True,False,False
4274,1,26.0,0,0.0,0.0,0.0,0.0,0.0,296,False,...,False,False,False,False,True,False,False,False,False,False
4275,0,26.0,0,0.0,2680.0,0.0,0.0,523.0,297,True,...,False,True,False,False,True,False,False,False,False,False
4276,1,43.0,0,0.0,0.0,0.0,0.0,0.0,1498,False,...,True,False,False,False,False,False,False,True,False,True

### Step 8: Feature Scaling
- Z-score standardisation

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler ()
X_test = test
X_test_scaled = scaler.fit_transform (X_test)

### Step 9: Predict

In [18]:
X_test_scaled_df = pd.DataFrame (X_test_scaled, columns = X_test.columns)
X_test_selected = X_test_scaled_df [selected_features]
predictions = model.predict (X_test_selected)

# Submission

In [19]:
submission = pd.DataFrame({
    "PassengerId": passenger_ids,
    "Transported": predictions
})

submission.to_csv("submission.csv", index=False)